const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');let W=innerWidth,H=innerHeight;canvas.width=W;canvas.height=H;addEventListener('resize',()=>{W=canvas.width=innerWidth;H=canvas.height=innerHeight});
const sprite=new Image();sprite.src='images%20(2).jpg';let spriteOK=false,aspect=2;sprite.onload=()=>{aspect=sprite.naturalWidth/(sprite.naturalHeight||1);spriteOK=true};
const input={x:0,y:0,bite:false,boost:false};let me='',world=3000,state={players:[],fish:[],hammerheads:[],lampreys:[],swarmers:[]},camera={x:0,y:0};
function pointer(e){input.x=(e.clientX-W/2)/Math.max(1,W/2);input.y=(e.clientY-H/2)/Math.max(1,H/2);const l=Math.hypot(input.x,input.y);if(l>1){input.x/=l;input.y/=l}}addEventListener('mousemove',pointer);addEventListener('mousedown',()=>input.bite=true);addEventListener('mouseup',()=>input.bite=false);addEventListener('keydown',e=>{if(e.code==='Space')input.bite=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')input.boost=true});addEventListener('keyup',e=>{if(e.code==='Space')input.bite=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')input.boost=false});
function connect(){const params=new URLSearchParams(location.search);const configured=params.get('server');let url;if(configured){url=configured}else if(location.protocol==='file:'||location.protocol==='chrome-extension:'){url='ws://localhost:3000'}else{const proto=location.protocol==='https:'?'wss':'ws';url=`${proto}://${location.host}`}status('CONNECTING...');let ws;try{ws=new WebSocket(url)}catch(e){status('SERVER CONNECTION ERROR');return}ws.onopen=()=>status('ONLINE');ws.onclose=()=>{status('SERVER DISCONNECTED');setTimeout(connect,2000)};ws.onerror=()=>status('CONNECTION ERROR');ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='welcome'){me=m.id;world=m.world;status('ONLINE')}if(m.type==='state')state=m}catch{}};window.sharkSocket=ws}
connect();
setInterval(()=>{const ws=window.sharkSocket;if(ws&&ws.readyState===1)ws.send(JSON.stringify({type:'input',x:input.x,y:input.y,bite:input.bite,boost:input.boost}))},50);
function status(t){const el=document.getElementById('status');if(el){el.textContent=t;el.classList.toggle('online',t==='ONLINE')}}
function mePlayer(){return state.players.find(p=>p.id===me)}function screen(e){return{x:e.x-camera.x,y:e.y-camera.y}}
function drawShark(x,y,a,size,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(a);if(spriteOK){const w=size,h=size/aspect;ctx.drawImage(sprite,-w/2,-h/2,w,h)}else{ctx.fillStyle='#9bdcf0';ctx.beginPath();ctx.ellipse(0,0,size*.5,size*.22,0,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawFish(f){const s=screen(f);if(s.x<-10||s.y<-10||s.x>W+10||s.y>H+10)return;ctx.fillStyle='#f6d66b';ctx.beginPath();ctx.arc(s.x,s.y,f.r,0,Math.PI*2);ctx.fill()}
function drawPred(p,type){const s=screen(p);if(s.x<-100||s.y<-100||s.x>W+100||s.y>H+100)return;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(p.angle||0);ctx.fillStyle=type==='hammerhead'?'#737f86':'#b94b68';ctx.beginPath();ctx.ellipse(0,0,p.r*1.45,p.r*.55,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=type==='hammerhead'?'#a9b4b8':'#ed7c92';ctx.beginPath();if(type==='hammerhead'){ctx.moveTo(-p.r*.7,-p.r*.25);ctx.lineTo(-p.r*1.5,-p.r*.75);ctx.lineTo(-p.r*1.5,p.r*.75);ctx.lineTo(-p.r*.7,p.r*.25)}else{ctx.moveTo(-p.r*.8,0);ctx.lineTo(-p.r*1.55,-p.r*.3);ctx.lineTo(-p.r*1.55,p.r*.3)}ctx.fill();ctx.restore()}
function drawWaiting(){ctx.fillStyle='#06364c';ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(110,210,230,.08)';for(let x=0;x<W;x+=100){ctx.fillRect(x,0,1,H)}for(let y=0;y<H;y+=100){ctx.fillRect(0,y,W,1)}ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 32px Arial';ctx.fillText('SHARKZ.IO',W/2,H/2-25);ctx.font='16px Arial';ctx.fillStyle='#9bdcf0';ctx.fillText('Connecting to Sharkz server...',W/2,H/2+15);ctx.font='13px Arial';ctx.fillStyle='#fff';ctx.fillText('Run SharkzServer.exe for multiplayer',W/2,H/2+45)}
function loop(){requestAnimationFrame(loop);const p=mePlayer();if(!p){drawWaiting();return}camera.x+=(p.x-W/2-camera.x)*.12;camera.y+=(p.y-H/2-camera.y)*.12;camera.x=Math.max(0,Math.min(Math.max(0,world-W),camera.x));camera.y=Math.max(0,Math.min(Math.max(0,world-H),camera.y));ctx.fillStyle='#06364c';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(110,210,230,.08)';for(let x=Math.floor(camera.x/100)*100;x<camera.x+W+100;x+=100){ctx.beginPath();ctx.moveTo(x-camera.x,0);ctx.lineTo(x-camera.x,H);ctx.stroke()}for(let y=Math.floor(camera.y/100)*100;y<camera.y+H+100;y+=100){ctx.beginPath();ctx.moveTo(0,y-camera.y);ctx.lineTo(W,y-camera.y);ctx.stroke()}
state.fish.forEach(drawFish);state.hammerheads.forEach(x=>drawPred(x,'hammerhead'));state.lampreys.forEach(x=>drawPred(x,'lamprey'));state.swarmers.forEach(x=>{const s=screen(x);drawShark(s.x,s.y,x.angle||0,Math.max(20,x.r*2.2),.72)});state.players.filter(x=>x.id!==me&&!x.dead).sort((a,b)=>b.weight-a.weight).forEach(x=>{const s=screen(x);drawShark(s.x,s.y,x.angle||0,Math.max(34,x.r*2.2),.92);ctx.fillStyle='#fff';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(`${x.name} • Lv ${x.level}`,s.x,s.y-x.r-12)});const ms=screen(p);drawShark(ms.x,ms.y,p.angle||0,Math.max(44,p.r*2.2),1);
const pct=Math.max(0,Math.min(1,p.health/p.maxHealth));document.getElementById('level').textContent=p.level;document.getElementById('xp').textContent=`${p.xp}/${p.nextXp}`;document.getElementById('weight').textContent=p.weight;document.getElementById('healthText').textContent=Math.ceil(p.health);document.getElementById('healthBar').style.width=`${pct*100}%`;document.getElementById('players').textContent=state.players.filter(x=>!x.dead).length;document.getElementById('gameOver').classList.toggle('hidden',!p.dead);const list=document.getElementById('leaderboard-list');list.innerHTML=state.players.filter(x=>!x.dead).sort((a,b)=>b.weight-a.weight).slice(0,6).map((x,i)=>`<li class=\"${x.id===me?'you':''}\">${i+1}. ${x.name} <b>${x.weight}</b></li>`).join('')}
loop();
