const http=require('http'),fs=require('fs'),path=require('path'),WebSocket=require('ws');
const PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'0.0.0.0',WORLD=3000,TICK=1000/30;
const ROOT=process.pkg?path.dirname(process.execPath):__dirname;
const players=new Map(),fish=[],hammerheads=[],lampreys=[],swarmers=[],babySharks=[];
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),d2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};
const send=(ws,d)=>{try{if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(d))}catch{}};
function newFish(id){const a=rand(0,Math.PI*2),speed=rand(18,38);return{id,x:rand(20,WORLD-20),y:rand(20,WORLD-20),vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:rand(4,7),xp:1}}
for(let i=0;i<350;i++)fish.push(newFish(`f${i}`));
for(let i=0;i<12;i++)hammerheads.push({id:`h${i}`,x:rand(100,WORLD-100),y:rand(100,WORLD-100),vx:0,vy:0,r:22,speed:48,health:180,maxHealth:180,attack:0,angle:0});
for(let i=0;i<18;i++)lampreys.push({id:`l${i}`,x:rand(100,WORLD-100),y:rand(100,WORLD-100),vx:0,vy:0,r:13,speed:55,health:90,maxHealth:90,phase:rand(0,Math.PI*2),target:null,attack:0,angle:0});
for(let i=0;i<24;i++)swarmers.push({id:`s${i}`,owner:null,x:rand(100,WORLD-100),y:rand(100,WORLD-100),vx:0,vy:0,r:9,speed:62,health:55,maxHealth:55,target:null,phase:rand(0,Math.PI*2),angle:0});
function spawnPlayer(ws){const id=Math.random().toString(36).slice(2,10);const p={id,name:`Shark-${id.slice(0,4)}`,x:rand(200,WORLD-200),y:rand(200,WORLD-200),vx:0,vy:0,r:18,weight:25,level:1,xp:0,nextXp:25,health:100,maxHealth:100,angle:0,dead:false,respawnAt:0,attack:0,input:{x:0,y:0,boost:false,bite:false},ws};players.set(id,p);for(let i=0;i<4;i++)babySharks.push({id:`b${id}-${i}`,owner:id,x:p.x,y:p.y,vx:0,vy:0,r:7,speed:145,angle:0,orbit:i*Math.PI/2,attack:0});return p}
function xp(p,n){p.xp+=n;while(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(p.nextXp*1.25);p.maxHealth+=5;p.health=p.maxHealth}}
function grow(p,n){p.weight+=n;p.r=14+Math.sqrt(p.weight)*1.35}
function kill(v,k){if(v.dead)return;v.dead=true;v.health=0;v.respawnAt=Date.now()+2500;if(k&&k!==v){xp(k,Math.max(10,Math.floor(v.weight*.9)));grow(k,Math.max(2,Math.floor(v.weight*.16)))}}
function nearest(x,y,max=Infinity,exclude=null){let b=null,bd=max*max;for(const p of players.values())if(!p.dead&&p!==exclude){const d=d2({x,y},p);if(d<bd){bd=d;b=p}}return b}
function nearestFish(x,y,max=Infinity){let b=null,bd=max*max;for(const f of fish){const d=d2({x,y},f);if(d<bd){bd=d;b=f}}return b}
function nearestAI(x,y,max=Infinity){let b=null,bd=max*max;for(const a of [...hammerheads,...lampreys,...swarmers]){if(a.dead)continue;const d=d2({x,y},a);if(d<bd){bd=d;b=a}}return b}
function nearestSwarmer(x,y,max=Infinity,excludeOwner=null){let b=null,bd=max*max;for(const s of swarmers){if(s.dead||s.owner===excludeOwner)continue;const d=d2({x,y},s);if(d<bd){bd=d;b=s}}return b}
function move(e,dt){e.x=clamp(e.x+e.vx*dt,e.r,WORLD-e.r);e.y=clamp(e.y+e.vy*dt,e.r,WORLD-e.r)}
function refill(){while(fish.length<350)fish.push(newFish(`f${Date.now()}-${Math.random()}`))}
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};
const httpServer=http.createServer((req,res)=>{let u=decodeURIComponent((req.url||'/').split('?')[0]);if(u==='/')u='/index.html';const file=path.resolve(ROOT,'.'+u);if(!file.startsWith(path.resolve(ROOT)+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,data)=>{if(e)return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(data)})});
const wss=new WebSocket.Server({server:httpServer});
wss.on('connection',ws=>{const p=spawnPlayer(ws);send(ws,{type:'welcome',id:p.id,world:WORLD});ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='input'&&!p.dead){p.input.x=clamp(Number(m.x)||0,-1,1);p.input.y=clamp(Number(m.y)||0,-1,1);p.input.boost=!!m.boost;p.input.bite=!!m.bite}}catch{}});ws.on('error',()=>{});ws.on('close',()=>{players.delete(p.id);for(let i=babySharks.length-1;i>=0;i--)if(babySharks[i].owner===p.id)babySharks.splice(i,1);for(const s of swarmers)if(s.owner===p.id)s.owner=null})});
let last=Date.now();setInterval(()=>{try{const now=Date.now(),dt=Math.min(.08,(now-last)/1000);last=now;
for(const f of fish){f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.x<f.r||f.x>WORLD-f.r)f.vx*=-1;if(f.y<f.r||f.y>WORLD-f.r)f.vy*=-1;const turn=(Math.random()-.5)*dt*1.5;const c=Math.cos(turn),s=Math.sin(turn),vx=f.vx*c-f.vy*s,vy=f.vx*s+f.vy*c;f.vx=vx;f.vy=vy}
for(const p of players.values()){if(p.dead){if(now>=p.respawnAt){p.dead=false;p.x=rand(200,WORLD-200);p.y=rand(200,WORLD-200);p.health=p.maxHealth}continue}const ix=p.input.x,iy=p.input.y,len=Math.hypot(ix,iy)||1,spd=p.input.boost?115:78;p.vx+=(ix/len*spd-p.vx)*Math.min(1,dt*7);p.vy+=(iy/len*spd-p.vy)*Math.min(1,dt*7);if(Math.abs(ix)+Math.abs(iy)>.05)p.angle=Math.atan2(iy,ix);move(p,dt);p.attack=Math.max(0,p.attack-dt);for(let i=fish.length-1;i>=0;i--){const f=fish[i];if(d2(p,f)<(p.r+f.r)**2){fish.splice(i,1);grow(p,f.xp*1.5);xp(p,f.xp*3)}}if(p.input.bite&&p.attack<=0){p.attack=.35;for(const o of players.values())if(o!==p&&!o.dead&&d2(p,o)<(p.r+o.r+18)**2){if(p.weight>=o.weight*.85){o.health-=Math.max(12,p.r*.55);if(o.health<=0)kill(o,p)}else p.health-=8}for(const a of [...hammerheads,...lampreys,...swarmers]){if(a.dead)continue;if(d2(p,a)<(p.r+a.r+20)**2){a.health-=Math.max(18,p.r*.65);if(a.health<=0){a.dead=true;xp(p,Math.max(3,Math.floor(a.r)));grow(p,1)}}}}if(p.health<p.maxHealth)p.health=Math.min(p.maxHealth,p.health+1.2*dt)}
for(const b of babySharks){const owner=players.get(b.owner);if(!owner||owner.dead)continue;const food=nearestFish(b.x,b.y,220),ai=nearestAI(b.x,b.y,320),enemyPlayer=nearest(b.x,b.y,320,owner),enemySwarmer=nearestSwarmer(b.x,b.y,320,owner.id);let target=null,targetType='';if(ai){target=ai;targetType='ai'}if(enemySwarmer&&(!target||d2(b,enemySwarmer)<d2(b,target)*.85)){target=enemySwarmer;targetType='swarmer'}if(enemyPlayer&&(!target||d2(b,enemyPlayer)<d2(b,target)*.75)){target=enemyPlayer;targetType='player'}if(food&&(!target||d2(b,food)<d2(b,target)*.6)){const dx=food.x-b.x,dy=food.y-b.y,l=Math.hypot(dx,dy)||1;b.vx+=(dx/l*b.speed-b.vx)*Math.min(1,dt*8);b.vy+=(dy/l*b.speed-b.vy)*Math.min(1,dt*8);b.angle=Math.atan2(b.vy,b.vx);move(b,dt);if(d2(b,food)<(b.r+food.r+4)**2){const i=fish.indexOf(food);if(i>=0)fish.splice(i,1);grow(owner,.5);xp(owner,2)}}else if(target){const dx=target.x-b.x,dy=target.y-b.y,l=Math.hypot(dx,dy)||1;b.vx+=(dx/l*b.speed-b.vx)*Math.min(1,dt*8);b.vy+=(dy/l*b.speed-b.vy)*Math.min(1,dt*8);b.angle=Math.atan2(b.vy,b.vx);move(b,dt);b.attack=Math.max(0,b.attack-dt);const hitRange=b.r+target.r+5;if(d2(b,target)<hitRange*hitRange&&b.attack<=0){b.attack=.55;if(targetType==='player'){target.health-=7;if(target.health<=0)kill(target,owner)}else{target.health-=targetType==='swarmer'?9:8;if(target.health<=0){target.dead=true;xp(owner,Math.max(3,Math.floor(target.r)));grow(owner,.75)}}}}else{b.orbit+=dt*1.8;const tx=owner.x+Math.cos(b.orbit)*38,ty=owner.y+Math.sin(b.orbit)*38,dx=tx-b.x,dy=ty-b.y,l=Math.hypot(dx,dy)||1;b.vx+=(dx/l*95-b.vx)*Math.min(1,dt*7);b.vy+=(dy/l*95-b.vy)*Math.min(1,dt*7);b.angle=Math.atan2(b.vy,b.vx);move(b,dt)}}
for(const h of hammerheads){if(h.dead)continue;const t=nearest(h.x,h.y,500);if(t){const dx=t.x-h.x,dy=t.y-h.y,l=Math.hypot(dx,dy)||1;h.vx+=(dx/l*h.speed-h.vx)*Math.min(1,dt*3);h.vy+=(dy/l*h.speed-h.vy)*Math.min(1,dt*3);h.angle=Math.atan2(h.vy,h.vx);move(h,dt);h.attack=Math.max(0,h.attack-dt);if(d2(h,t)<(h.r+t.r)**2&&h.attack<=0){h.attack=.65;t.health-=18;if(t.health<=0)kill(t,null)}}else{h.vx*=.98;h.vy*=.98;move(h,dt)}}
for(const l of lampreys){if(l.dead)continue;if(!l.target||l.target.dead||Math.random()<.02)l.target=nearest(l.x,l.y,500);const t=l.target;if(t){const a=Math.atan2(t.y-l.y,t.x-l.x)+Math.PI/2;l.phase+=dt*2.7;const tx=t.x+Math.cos(a)*55,ty=t.y+Math.sin(a)*55,aa=Math.atan2(ty-l.x,tx-l.y);l.vx+=(Math.cos(aa)*l.speed+Math.cos(l.phase)*18-l.vx)*Math.min(1,dt*4);l.vy+=(Math.sin(aa)*l.speed+Math.sin(l.phase)*18-l.vy)*Math.min(1,dt*4);l.angle=Math.atan2(l.vy,l.vx);move(l,dt);l.attack=Math.max(0,l.attack-dt);if(d2(l,t)<(l.r+t.r+6)**2&&l.attack<=0){l.attack=.7;t.health-=12;if(t.health<=0)kill(t,null)}}}
for(const s of swarmers){if(s.dead)continue;if(!s.target||s.target.dead||Math.random()<.03)s.target=nearest(s.x,s.y,900);const t=s.target;if(t){const a=Math.atan2(t.y-s.y,t.x-s.x);s.phase+=dt*5;s.vx+=(Math.cos(a)*s.speed+Math.cos(s.phase)*30-s.vx)*Math.min(1,dt*2.5);s.vy+=(Math.sin(a)*s.speed+Math.sin(s.phase)*30-s.vy)*Math.min(1,dt*2.5);s.angle=Math.atan2(s.vy,s.vx);move(s,dt)}}
refill();const state={type:'state',players:[...players.values()].map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,r:p.r,weight:Math.round(p.weight),level:p.level,xp:p.xp,nextXp:p.nextXp,health:Math.max(0,p.health),maxHealth:p.maxHealth,angle:p.angle,dead:p.dead})),fish,hammerheads:hammerheads.filter(x=>!x.dead),lampreys:lampreys.filter(x=>!x.dead),swarmers:swarmers.filter(x=>!x.dead),babySharks};for(const p of players.values())send(p.ws,state)
}catch(err){console.error('Sharkz tick error:',err)}} ,TICK);
httpServer.on('error',err=>console.error('Sharkz HTTP server error:',err));
httpServer.listen(PORT,HOST,()=>console.log(`Sharkz.io server on port ${PORT}`));